(* begin-package-description

The Draft package provides:

* An environment for editing drafts of novels and screenplays

end-package-description *)

(* begin-module-short-description
provides a novel and screenplay editor.
end-module-short-description *)

(* begin-module-use-description
Module Draft provides:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Draft; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Draft.
