(* begin-documentation-node
############
  Examples
############


.. toctree::
   :maxdepth: 2
   :caption: Development:
   :includehidden:

   Arithmetic    [Course/Arithmetic.rst]
   Functions     [Course/Functions.rst]

A course of programming examples starts here...

https://github.com/io-core/Examples/blob/main/Course.Mod

end-documentation-node *)



(* begin-module-use-description
Module Course handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Course; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Course.
