(* begin-package-description
### _Package Overview:_
The Examples package manages:
* Showing how to program in Oberon
### _Package Use:_

Explanation...

end-package-description *)

(* begin-module-use-description
Module Examples handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Examples; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Examples.
