(* begin-package-description
### _Package Overview:_
The Assist package manages:
* contributions
### _Package Use:_

Explanation...

### _Modules in this package:_
end-package-description *)

(* begin-module-short-description
provides help functionality in the UI.
end-module-short-description *)

(* begin-module-use-description
Module Assist handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Assist; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Assist.
