(* begin-documentation-node
###########################
  Usage
###########################


.. toctree::
   :maxdepth: 2
   :caption: Development:
   :includehidden:

   ../Assist/Sup    <Startup.rst>
   ../Assist/Nav    <Navigating.rst>
   ../Assist/Doc    <Documents.rst>
   ../Assist/Fac    <Facets.rst>
   ../Assist/Net    <Networking.rst>

* Startup and Shutdown
* Navigating the UI
* Commands in IO
* Working with documents
* Facets of IO
* File exchange and networking

https://github.com/io-core/Assist/blob/main/Hello.Mod

end-documentation-node *)

(* begin-module-short-description
provides help functionality in the UI.
end-module-short-description *)

(* begin-package-description
### _Package Overview:_
The Assist package manages:
* contributions
### _Package Use:_

Explanation...

### _Modules in this package:_
end-package-description *)

(* begin-module-use-description
Module Hello handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Hello; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Hello.
