(* begin-documentation-node
###########################
  Usage
###########################

Startup and Shutdown
====================

Navigating the UI
=================

Commands
========

Working with documents
======================

Applications
============

File exchange and networking
============================

https://github.com/io-core/Assist/blob/main/Hello.Mod

end-documentation-node *)

(* begin-module-short-description
provides help functionality in the UI.
end-module-short-description *)

(* begin-module-use-description
Module Hello handles:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE Hello; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Hello.
