(* begin-documentation-node
#############
  Community
#############

Mailing Lists
=============

Websites
========

Docbooks
========

Reporting Bugs
==============

https://github.com/io-core/Net/blob/main/Report.Mod

end-documentation-node *)


(* begin-package-description
### _Package Overview:_
The Net package manages:
* Internetworking Integrated Oberon
* Basic tools for using the network
### _Package Use:_

USAGE:
```
(provide example)

```

### _Modules in this package:_
end-package-description *)

(* begin-module-use-description
Module Discuss handles:
* Nothing yet. Bug reporting eventually.

end-module-use-description *)
MODULE Report; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Report.
