(* begin-package-description

The BASIC package provides:

* A compiler for ECMA-55 BASIC
* A command for compiling, running and interacting with BASIC programs

end-package-description *)

(* begin-module-short-description
provides ECMA-55 BASIC.
end-module-short-description *)

(* begin-module-use-description
Module BASIC provides:
* Nothing yet. Placeholder.

end-module-use-description *)
MODULE BASIC; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-section-description
## ---------- Generate Documentation
  end-section-description *)

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END BASIC.
