(* begin-module-short-description
fuzzing definition, execution, and reporting
end-module-short-description *)

(* begin-module-use-description
Module Fuzzing handles:

* Nothing yet. Module fuzzing eventually.

end-module-use-description *)
MODULE Fuzzing; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Fuzzing.
