(* begin-module-short-description
Performance instrumentation and reporting
end-module-short-description *)

(* begin-module-use-description
Module Performance handles:

* Nothing yet. Performance monitoring eventually.

end-module-use-description *)
MODULE Performance; 
  IMPORT SYSTEM;

  CONST 

  TYPE 

  VAR 

  (* begin-procedure-description
---
**Foo** is a placeholder
  end-procedure-description *)
  PROCEDURE Foo;
  BEGIN 
  END Foo;



END Performance.
